/**
 * Banco de preguntas de la trivia. Cada partida sortea del banco una pregunta por cada
 * lugar de `GAME_TEMPLATE` (config.ts), sin repetir. Para agregar una pregunta, sumala
 * a la lista con un `id` único y estable: las partidas guardan los ids en Supabase.
 *
 * - `mc`: cuatro opciones, `answer` es el índice de la correcta (0 = A).
 * - `tf`: una afirmación y si es verdadera.
 * - `price`: el precio justo. El precio es fijo por ruta (calculado con el motor de precios
 *   de Movo, ver abajo); `breakdown` es la línea "Cómo lo calcula Movo" de la revelación y es
 *   opcional.
 *   `from` y `to` tienen que estar en `localidades.ts` para dibujar la ruta en el mapa.
 *
 * `fact` es el "Dato Movo" que se muestra en la revelación (TV y celular).
 */

export interface ChoiceQuestion {
  id: string
  type: "mc"
  prompt: string
  options: [string, string, string, string]
  answer: 0 | 1 | 2 | 3
  fact: string
}

export interface TrueFalseQuestion {
  id: string
  type: "tf"
  prompt: string
  answer: boolean
  fact: string
}

export interface PriceQuestion {
  id: string
  type: "price"
  from: string
  to: string
  km: number
  parcel: string
  /** Precio real en pesos. */
  price: number
  breakdown?: string
  /** Rango del slider en el celular y en la recta de la revelación. */
  min: number
  max: number
}

export type Question = ChoiceQuestion | TrueFalseQuestion | PriceQuestion
export type QuestionType = Question["type"]

export const PRICE_PROMPT = "¿Cuánto sale mandarlo con Movo?"

export const QUESTIONS: Question[] = [
  // Multiple choice
  {
    id: "mc-que-es",
    type: "mc",
    prompt: "Movo conecta a quien quiere mandar un paquete con…",
    options: [
      "Una flota de motos propia",
      "Alguien que ya viaja a ese destino",
      "Una sucursal de correo",
      "Drones",
    ],
    answer: 1,
    fact: "El viaje ya iba a ocurrir. Movo aprovecha el espacio libre en el auto o la mochila.",
  },
  {
    id: "mc-que-mandar",
    type: "mc",
    prompt: "¿Cuál de estos envíos es ideal para Movo?",
    options: [
      "Una mudanza completa",
      "Una heladera",
      "Una llave de repuesto a otra ciudad",
      "Un auto",
    ],
    answer: 2,
    fact: "Movo está pensado para objetos chicos: documentos, llaves, cargadores, regalos.",
  },
  {
    id: "mc-kyc",
    type: "mc",
    prompt: "¿Qué te pide Movo para verificar tu identidad?",
    options: [
      "Solo tu mail",
      "DNI y una selfie",
      "Un recibo de sueldo",
      "Nada, es anónimo",
    ],
    answer: 1,
    fact: "Un sistema de detección de vida confirma que hay una persona real y no una foto.",
  },
  {
    id: "mc-handshake",
    type: "mc",
    prompt: "¿Cómo se confirma que un paquete cambió de manos?",
    options: [
      "Con un botón de confirmar",
      "Con una foto del paquete",
      "Con un QR firmado y el GPS de los dos celulares",
      "Llamando por teléfono",
    ],
    answer: 2,
    fact: "El Cryptographic Handshake exige que los dos teléfonos estén juntos en ese momento.",
  },
  {
    id: "mc-cobro",
    type: "mc",
    prompt: "¿Cuándo se le cobra el envío a quien lo manda?",
    options: [
      "Al publicarlo",
      "Cuando se entrega",
      "Cuando lo retiran",
      "A fin de mes",
    ],
    answer: 1,
    fact: "El monto queda reservado en la tarjeta y se cobra recién al confirmar la entrega.",
  },
  {
    id: "mc-comision",
    type: "mc",
    prompt: "¿De qué vive Movo?",
    options: [
      "De publicidad",
      "De una suscripción mensual",
      "De vender datos",
      "De una comisión por envío entregado",
    ],
    answer: 3,
    fact: "Movo gana solo cuando el envío llega. Así los incentivos quedan alineados.",
  },
  {
    id: "mc-ruta",
    type: "mc",
    prompt: "Si declarás un viaje, ¿qué hace el algoritmo de Movo?",
    options: [
      "Te cambia el destino",
      "Te suma paquetes con el menor desvío posible",
      "Te asigna un camión",
      "Te cobra el combustible",
    ],
    answer: 1,
    fact: "Un viaje de Córdoba a Luque puede sumar una parada en Villa del Rosario con solo 6 km de desvío.",
  },
  {
    id: "mc-calificaciones",
    type: "mc",
    prompt: "Después de cada entrega, ¿quiénes se califican?",
    options: [
      "Nadie",
      "Solo quien manda",
      "Quien manda, quien lleva y quien recibe",
      "Solo Movo",
    ],
    answer: 2,
    fact: "Las calificaciones arman una reputación pública hecha con envíos reales.",
  },
  {
    id: "mc-receptor",
    type: "mc",
    prompt: "¿Qué tiene que pasar antes de que un envío se publique?",
    options: [
      "Que lo apruebe un operador",
      "Que el receptor acepte recibirlo",
      "Que pagues por adelantado",
      "Nada, se publica al toque",
    ],
    answer: 1,
    fact: "Así nadie recibe un paquete que no pidió.",
  },
  {
    id: "mc-precio",
    type: "mc",
    prompt: "¿Qué NO usa el motor de precios para sugerir un valor?",
    options: ["La distancia", "El peso", "La urgencia", "El color del paquete"],
    answer: 3,
    fact: "Distancia, peso, urgencia y categoría. Después los transportistas pueden contraofertar.",
  },
  // Verdadero o falso
  {
    id: "tf-emisiones",
    type: "tf",
    prompt:
      "Si un viajero ya iba a Río Cuarto, llevar tu paquete prácticamente no agrega emisiones.",
    answer: true,
    fact: "El auto iba a hacer ese viaje igual. Un paquete más casi no cambia lo que consume.",
  },
  {
    id: "tf-dni",
    type: "tf",
    prompt: "Movo guarda las fotos de tu DNI en sus servidores.",
    answer: false,
    fact: "Las procesa un proveedor especializado. Movo solo recibe si la verificación salió bien.",
  },
  {
    id: "tf-efectivo",
    type: "tf",
    prompt: "Con Movo se puede pagar un envío en efectivo.",
    answer: true,
    fact: "El receptor le paga en mano al transportista al momento de la entrega.",
  },
  {
    id: "tf-blockchain",
    type: "tf",
    prompt: "Movo usa blockchain para confirmar las entregas.",
    answer: false,
    fact: "Alcanza con firmas digitales y un registro con hash criptográfico. Más simple e igual de seguro.",
  },
  {
    id: "tf-cancelar",
    type: "tf",
    prompt:
      "Podés cancelar un envío sin penalidad antes de que se asigne un transportista.",
    answer: true,
    fact: "La penalidad aparece recién cuando alguien ya se comprometió a llevarlo.",
  },
  {
    id: "tf-repartidores",
    type: "tf",
    prompt: "Movo tiene repartidores propios en cada ciudad.",
    answer: false,
    fact: "La red la forman los mismos usuarios que ya viajan.",
  },
  {
    id: "tf-licencia",
    type: "tf",
    prompt:
      "Para llevar paquetes con Movo hay que verificar la licencia de conducir.",
    answer: true,
    fact: "Además de la identidad, quien transporta verifica su licencia y carga una tarjeta.",
  },
  {
    id: "tf-qr",
    type: "tf",
    prompt: "El QR de la entrega dura solo unos segundos en pantalla.",
    answer: true,
    fact: "Un código de vida corta evita que alguien lo reutilice más tarde.",
  },
  {
    id: "mc-quien-decide-precio",
    type: "mc",
    prompt: "¿Quién decide el precio final de un envío?",
    options: [
      "Lo fija Movo y no se puede cambiar",
      "Lo define siempre el receptor",
      "Es un precio fijo por kilómetro",
      "Lo sugiere el sistema y los transportistas pueden contraofertar",
    ],
    answer: 3,
    fact: "Movo sugiere un valor y la oferta final se acuerda entre las partes.",
  },
  {
    id: "mc-primer-paso",
    type: "mc",
    prompt: "¿Cuál es el primer paso para mandar algo por Movo?",
    options: [
      "Publicar el envío con origen, destino y qué llevás",
      "Elegir un transportista de una lista",
      "Pagar por adelantado",
      "Ir a una sucursal",
    ],
    answer: 0,
    fact: "El envío se publica y después se asigna a alguien que ya viaja hacia ese destino.",
  },
  {
    id: "mc-nadie-acepta",
    type: "mc",
    prompt: "¿Qué pasa si nadie acepta tu envío?",
    options: [
      "Movo lo entrega con repartidores propios",
      "Se cobra igual",
      "No se cobra nada y podés ajustar la oferta o cancelar",
      "Se cancela solo y pagás una multa",
    ],
    answer: 2,
    fact: "Sin transportista asignado no hay compromiso, ni cobro ni penalidad.",
  },
  {
    id: "mc-aceptacion-receptor",
    type: "mc",
    prompt: "¿Quién tiene que aceptar el envío antes de que se publique?",
    options: ["Un operador de Movo", "Un vecino", "Nadie", "El receptor"],
    answer: 3,
    fact: "El receptor confirma que quiere recibirlo, así nadie recibe algo que no pidió.",
  },
  {
    id: "mc-roles",
    type: "mc",
    prompt: "¿Qué tres roles participan en cada envío?",
    options: [
      "Cliente, operador y soporte",
      "Quien manda, quien lleva y quien recibe",
      "Comprador, vendedor y árbitro",
      "Piloto, copiloto y pasajero",
    ],
    answer: 1,
    fact: "Cada rol tiene su parte del proceso y todos se califican al final.",
  },
  {
    id: "mc-viaje-programado",
    type: "mc",
    prompt: "¿Qué necesita una persona para ofrecerse a llevar paquetes?",
    options: [
      "Tener un viaje programado hacia el destino",
      "Solo bajar la app",
      "Tener una empresa",
      "Tener una camioneta",
    ],
    answer: 0,
    fact: "Declarar un viaje es lo que habilita sumar envíos en el camino.",
  },
  {
    id: "mc-seguimiento",
    type: "mc",
    prompt: "¿Para qué sirve el seguimiento en tiempo real?",
    options: [
      "Para ver los viajes de otros usuarios",
      "Para cobrar peaje",
      "Para calificar rutas",
      "Para ver por dónde viene tu paquete",
    ],
    answer: 3,
    fact: "Podés seguir el avance del envío sin tener que escribirle al transportista.",
  },

  // ---- Nuevas: confianza y seguridad ----
  {
    id: "mc-sin-proximidad",
    type: "mc",
    prompt:
      "¿Qué pasa si el transportista y el receptor no están juntos en el momento de la entrega?",
    options: [
      "No se puede confirmar la entrega",
      "Se confirma igual",
      "Se confirma a las 24 horas",
      "Se cobra doble",
    ],
    answer: 0,
    fact: "La entrega exige QR y proximidad por GPS de los dos teléfonos al mismo tiempo.",
  },
  {
    id: "mc-claves",
    type: "mc",
    prompt: "¿Dónde se generan las claves criptográficas de tu cuenta?",
    options: [
      "En un servidor de Movo",
      "En tu casilla de mail",
      "En la tarjeta",
      "En tu celular",
    ],
    answer: 3,
    fact: "Firmar una entrega requiere tener tu teléfono, no alcanza con conocer una contraseña.",
  },
  {
    id: "mc-respaldo-fotos",
    type: "mc",
    prompt: "¿Qué respaldo queda de cada entrega además del QR?",
    options: [
      "Un video de un minuto",
      "Una firma en papel",
      "Fotos del paquete",
      "Ninguno",
    ],
    answer: 2,
    fact: "La evidencia fotográfica ayuda a resolver cualquier reclamo después.",
  },
  {
    id: "mc-hash",
    type: "mc",
    prompt: "¿Qué hace difícil alterar el registro de una entrega?",
    options: [
      "Una planilla compartida",
      "Un sello de goma",
      "Una contraseña de admin",
      "Un hash criptográfico",
    ],
    answer: 3,
    fact: "Si alguien tocara el registro, el hash dejaría de coincidir y se notaría.",
  },

  // ---- Nuevas: pagos y precios ----
  {
    id: "mc-pasarela",
    type: "mc",
    prompt: "¿Qué plataforma procesa los pagos con tarjeta en Movo?",
    options: ["Transferencia manual", "Criptomonedas", "Mercado Pago", "Cheques"],
    answer: 2,
    fact: "Es la pasarela que reserva y cobra el envío.",
  },
  {
    id: "mc-momento-reserva",
    type: "mc",
    prompt: "¿Cuándo se reserva el monto en la tarjeta?",
    options: [
      "Un día antes de que retiren el paquete",
      "Al publicar el envío",
      "Al registrarte",
      "Una semana antes",
    ],
    answer: 0,
    fact: "Reservar cerca del retiro evita que la reserva venza si el retiro está lejos.",
  },
  {
    id: "mc-reservado",
    type: "mc",
    prompt: "¿Qué significa que el monto esté reservado?",
    options: [
      "Que ya se descontó de tu cuenta",
      "Que el transportista ya lo cobró",
      "Que se devolvió",
      "Que queda bloqueado en la tarjeta pero todavía no se descuenta",
    ],
    answer: 3,
    fact: "El cobro real ocurre recién cuando se confirma la entrega.",
  },
  {
    id: "mc-contraoferta",
    type: "mc",
    prompt: "¿Quién puede contraofertar el precio sugerido?",
    options: ["Solo Movo", "Los transportistas", "Nadie", "Solo el receptor"],
    answer: 1,
    fact: "El precio sugerido es un punto de partida, no una imposición.",
  },
  {
    id: "mc-factor-precio",
    type: "mc",
    prompt: "¿Qué factor puede subir el precio sugerido de un envío?",
    options: [
      "Que sea urgente",
      "Que sea lunes",
      "Que el paquete tenga moño",
      "Que el receptor tenga muchas calificaciones",
    ],
    answer: 0,
    fact: "Distancia, peso, urgencia y categoría pesan en el valor sugerido.",
  },
  {
    id: "mc-efectivo",
    type: "mc",
    prompt: "En un pago en efectivo, ¿quién le paga al transportista?",
    options: [
      "Movo, por adelantado",
      "Una empresa aliada",
      "El receptor, en mano al recibir",
      "Nadie, es gratis",
    ],
    answer: 2,
    fact: "El efectivo se entrega en el momento de la entrega, cara a cara.",
  },

  // ---- Nuevas: rutas, comunidad e impacto ----
  {
    id: "mc-algoritmo-paradas",
    type: "mc",
    prompt: "¿Qué tiene en cuenta el algoritmo al sumar paradas a tu viaje?",
    options: [
      "El desvío y los horarios de retiro y entrega",
      "El color del auto",
      "La música que escuchás",
      "El clima en Marte",
    ],
    answer: 0,
    fact: "Busca la ruta que cumpla las ventanas horarias con el menor recorrido extra.",
  },
  {
    id: "mc-destino-viaje",
    type: "mc",
    prompt: "Si sumás un paquete a tu viaje, ¿qué pasa con tu destino?",
    options: [
      "Cambia al del paquete",
      "Te suman un acompañante",
      "Se cancela el viaje",
      "Seguís hacia el mismo destino, con paradas cortas en el camino",
    ],
    answer: 3,
    fact: "El viaje sigue siendo tuyo; el paquete se acomoda a tu ruta y no al revés.",
  },
  {
    id: "mc-reputacion-publica",
    type: "mc",
    prompt: "¿Quién puede ver la reputación de un usuario?",
    options: [
      "Solo Movo",
      "Solo su familia",
      "Cualquier usuario de la app",
      "Nadie",
    ],
    answer: 2,
    fact: "Una reputación pública se construye con envíos reales y ayuda a elegir con quién tratar.",
  },
  {
    id: "mc-emisiones",
    type: "mc",
    prompt: "¿Por qué un envío con Movo suma menos emisiones que uno tradicional?",
    options: [
      "Aprovecha un viaje que ya iba a ocurrir",
      "Usa autos eléctricos",
      "Planta un árbol por envío",
      "Viaja en tren",
    ],
    answer: 0,
    fact: "No se agrega un viaje nuevo: se usa espacio que ya iba libre.",
  },
  {
    id: "mc-ganancia-transportista",
    type: "mc",
    prompt: "¿Qué gana quien lleva un paquete con Movo?",
    options: [
      "Un auto nuevo",
      "Un ingreso por espacio que ya iba libre",
      "Descuento en la patente",
      "Nada",
    ],
    answer: 1,
    fact: "Convierte un lugar vacío del auto o la mochila en plata.",
  },

  // ---- Nuevas: verdadero o falso ----
  {
    id: "tf-varios-paquetes",
    type: "tf",
    prompt: "Un mismo viaje puede llevar paquetes de varias personas.",
    answer: true,
    fact: "El algoritmo arma varias paradas en una sola ruta, siempre que el desvío sea chico.",
  },
  {
    id: "tf-seguimiento",
    type: "tf",
    prompt: "El receptor puede seguir el envío en tiempo real.",
    answer: true,
    fact: "El seguimiento en vivo muestra por dónde viene el paquete.",
  },
  {
    id: "tf-receptor-no-sabe",
    type: "tf",
    prompt: "Se puede publicar un envío sin que el receptor se entere.",
    answer: false,
    fact: "El receptor tiene que aceptar recibirlo antes de que se publique.",
  },
  {
    id: "tf-clave-privada",
    type: "tf",
    prompt: "Movo guarda tu clave privada en sus servidores.",
    answer: false,
    fact: "Las claves se generan en tu celular y firman las entregas desde ahí.",
  },
  {
    id: "tf-precio-distinto",
    type: "tf",
    prompt: "Los transportistas pueden proponer un precio distinto al sugerido.",
    answer: true,
    fact: "El sistema sugiere y las partes negocian con contraofertas.",
  },
  {
    id: "tf-mensaje-alcanza",
    type: "tf",
    prompt: "Para entregar un envío alcanza con mandarle un mensaje al receptor.",
    answer: false,
    fact: "Hace falta el QR firmado y que los dos teléfonos estén juntos.",
  },
  {
    id: "tf-sin-cercania",
    type: "tf",
    prompt:
      "Si el transportista y el receptor no están juntos, la entrega no se puede confirmar.",
    answer: true,
    fact: "La proximidad por GPS es parte de la validación.",
  },
  {
    id: "tf-comision-sin-entrega",
    type: "tf",
    prompt: "Movo cobra su comisión aunque el envío no llegue.",
    answer: false,
    fact: "Movo gana solo cuando el envío se entrega.",
  },
  {
    id: "tf-reserva-descuenta",
    type: "tf",
    prompt:
      "Si el monto está reservado en tu tarjeta, ya se descontó de tu cuenta.",
    answer: false,
    fact: "La reserva bloquea el monto; el cobro se hace al confirmar la entrega.",
  },
  // El precio justo. Precios del motor de Movo (demand_fuel_routes_v1, mismo código y
  // coeficientes que movo-svc-pricing-logistics) calculados el 3/10/2026: nafta súper a
  // $2.227/l (mediana nacional de Energía), distancia por ruta (OSRM) y sin recargo por
  // demanda. El slider tiene un rango distinto en cada ruta para que el precio no quede
  // siempre en el mismo lugar.
    {
    id: "price-cordoba-villa-carlos-paz-letter",
    type: "price",
    from: "Córdoba",
    to: "Villa Carlos Paz",
    km: 37,
    parcel: "Sobre · documentos",
    price: 5190,
    breakdown: "$1.525 base + 37 km × $95 + 0,5 kg × $300",
    min: 4500,
    max: 17500,
  },
  {
    id: "price-cordoba-villa-carlos-paz-small",
    type: "price",
    from: "Córdoba",
    to: "Villa Carlos Paz",
    km: 37,
    parcel: "Caja chica · 2 kg",
    price: 5640,
    breakdown: "$1.523 base + 37 km × $95 + 2 kg × $301",
    min: 500,
    max: 12000,
  },
  {
    id: "price-cordoba-jesus-maria-small",
    type: "price",
    from: "Córdoba",
    to: "Jesús María",
    km: 56,
    parcel: "Caja chica · 2 kg",
    price: 5090,
    breakdown: "$1.520 base + 56 km × $53 + 2 kg × $301",
    min: 4000,
    max: 21000,
  },
  {
    id: "price-cordoba-alta-gracia-fragile",
    type: "price",
    from: "Córdoba",
    to: "Alta Gracia",
    km: 38,
    parcel: "Frágil · 3 kg",
    price: 4689,
    breakdown: "($1.522,50 base + 38 km × $39 + 3 kg × $301) × 1,2 por frágil",
    min: 500,
    max: 13500,
  },
  {
    id: "price-cordoba-rio-ceballos-letter",
    type: "price",
    from: "Córdoba",
    to: "Río Ceballos",
    km: 35,
    parcel: "Sobre · documentos",
    price: 3910,
    breakdown: "$1.520 base + 35 km × $64 + 0,5 kg × $300",
    min: 500,
    max: 14000,
  },
  {
    id: "price-cordoba-villa-maria-small",
    type: "price",
    from: "Córdoba",
    to: "Villa María",
    km: 150,
    parcel: "Caja chica · 2 kg",
    price: 4305,
    breakdown: "$1.603 base + 150 km × $14 + 2 kg × $301",
    min: 12000,
    max: 57000,
  },
  {
    id: "price-cordoba-villa-maria-medium",
    type: "price",
    from: "Córdoba",
    to: "Villa María",
    km: 150,
    parcel: "Caja mediana · 8 kg",
    price: 5430,
    breakdown: "$1.522 base + 150 km × $10 + 8 kg × $301",
    min: 1000,
    max: 40000,
  },
  {
    id: "price-cordoba-rio-cuarto-letter",
    type: "price",
    from: "Córdoba",
    to: "Río Cuarto",
    km: 213,
    parcel: "Sobre · documentos",
    price: 8323,
    breakdown: "$1.570 base + 213 km × $31 + 0,5 kg × $300",
    min: 5000,
    max: 59000,
  },
  {
    id: "price-cordoba-rio-tercero-small",
    type: "price",
    from: "Córdoba",
    to: "Río Tercero",
    km: 108,
    parcel: "Caja chica · 2 kg",
    price: 6302,
    breakdown: "$1.596 base + 108 km × $38 + 2 kg × $301",
    min: 4000,
    max: 48000,
  },
  {
    id: "price-cordoba-san-francisco-fragile",
    type: "price",
    from: "Córdoba",
    to: "San Francisco",
    km: 217,
    parcel: "Frágil · 3 kg",
    price: 5789,
    breakdown: "($1.534 base + 217 km × $11 + 3 kg × $301) × 1,2 por frágil",
    min: 2500,
    max: 55000,
  },
  {
    id: "price-cordoba-cosquin-small",
    type: "price",
    from: "Córdoba",
    to: "Cosquín",
    km: 52,
    parcel: "Caja chica · 2 kg",
    price: 6479,
    breakdown: "$1.509 base + 52 km × $84 + 2 kg × $301",
    min: 2500,
    max: 20500,
  },
  {
    id: "price-cordoba-villa-general-belgrano-medium",
    type: "price",
    from: "Córdoba",
    to: "Villa General Belgrano",
    km: 87,
    parcel: "Caja mediana · 8 kg",
    price: 7699,
    breakdown: "$1.550 base + 87 km × $43 + 8 kg × $301",
    min: 1000,
    max: 29000,
  },
  {
    id: "price-cordoba-mina-clavero-small",
    type: "price",
    from: "Córdoba",
    to: "Mina Clavero",
    km: 142,
    parcel: "Caja chica · 2 kg",
    price: 5782,
    breakdown: "$1.630 base + 142 km × $25 + 2 kg × $301",
    min: 14000,
    max: 52000,
  },
  {
    id: "price-cordoba-rosario-small",
    type: "price",
    from: "Córdoba",
    to: "Rosario",
    km: 405,
    parcel: "Caja chica · 2 kg",
    price: 8738,
    breakdown: "$1.656 base + 405 km × $16 + 2 kg × $301",
    min: 2500,
    max: 90000,
  },
  {
    id: "price-cordoba-rosario-medium",
    type: "price",
    from: "Córdoba",
    to: "Rosario",
    km: 405,
    parcel: "Caja mediana · 8 kg",
    price: 9875,
    breakdown: "$1.797 base + 405 km × $14 + 8 kg × $301",
    min: 17500,
    max: 147500,
  },
  {
    id: "price-cordoba-buenos-aires-letter",
    type: "price",
    from: "Córdoba",
    to: "Buenos Aires",
    km: 696,
    parcel: "Sobre · documentos",
    price: 11234,
    breakdown: "$1.340 base + 696 km × $14 + 0,5 kg × $300",
    min: 65000,
    max: 257500,
  },
  {
    id: "price-cordoba-buenos-aires-fragile",
    type: "price",
    from: "Córdoba",
    to: "Buenos Aires",
    km: 696,
    parcel: "Frágil · 3 kg",
    price: 13245,
    breakdown: "($1.782,50 base + 696 km × $12 + 3 kg × $301) × 1,2 por frágil",
    min: 2500,
    max: 210000,
  },
  {
    id: "price-cordoba-mendoza-small",
    type: "price",
    from: "Córdoba",
    to: "Mendoza",
    km: 687,
    parcel: "Caja chica · 2 kg",
    price: 16320,
    breakdown: "$1.291 base + 687 km × $21 + 2 kg × $301",
    min: 42500,
    max: 212500,
  },
  {
    id: "price-cordoba-san-miguel-de-tucuman-small",
    type: "price",
    from: "Córdoba",
    to: "San Miguel de Tucumán",
    km: 562,
    parcel: "Caja chica · 2 kg",
    price: 14982,
    breakdown: "$1.454 base + 562 km × $23 + 2 kg × $301",
    min: 2500,
    max: 120000,
  },
  {
    id: "price-cordoba-santa-fe-letter",
    type: "price",
    from: "Córdoba",
    to: "Santa Fe",
    km: 364,
    parcel: "Sobre · documentos",
    price: 12340,
    breakdown: "$1.634 base + 364 km × $29 + 0,5 kg × $300",
    min: 5000,
    max: 117500,
  },
  {
    id: "price-cordoba-san-luis-medium",
    type: "price",
    from: "Córdoba",
    to: "San Luis",
    km: 428,
    parcel: "Caja mediana · 8 kg",
    price: 12349,
    breakdown: "$1.381 base + 428 km × $20 + 8 kg × $301",
    min: 35000,
    max: 157500,
  },
  {
    id: "price-cordoba-santiago-del-estero-small",
    type: "price",
    from: "Córdoba",
    to: "Santiago del Estero",
    km: 435,
    parcel: "Caja chica · 2 kg",
    price: 14203,
    breakdown: "$1.421 base + 435 km × $28 + 2 kg × $301",
    min: 2500,
    max: 102500,
  },
  {
    id: "price-rio-cuarto-villa-maria-letter",
    type: "price",
    from: "Río Cuarto",
    to: "Villa María",
    km: 136,
    parcel: "Sobre · documentos",
    price: 6922,
    breakdown: "$1.468 base + 136 km × $39 + 0,5 kg × $300",
    min: 3000,
    max: 39000,
  },
  {
    id: "price-villa-maria-bell-ville-small",
    type: "price",
    from: "Villa María",
    to: "Bell Ville",
    km: 63,
    parcel: "Caja chica · 2 kg",
    price: 7822,
    breakdown: "$1.487 base + 63 km × $91 + 2 kg × $301",
    min: 2500,
    max: 30500,
  },
  {
    id: "price-rosario-santa-fe-small",
    type: "price",
    from: "Rosario",
    to: "Santa Fe",
    km: 172,
    parcel: "Caja chica · 2 kg",
    price: 8927,
    breakdown: "$1.445 base + 172 km × $40 + 2 kg × $301",
    min: 1000,
    max: 37000,
  },
  {
    id: "price-buenos-aires-la-plata-letter",
    type: "price",
    from: "Buenos Aires",
    to: "La Plata",
    km: 58,
    parcel: "Sobre · documentos",
    price: 10410,
    breakdown: "$1.502 base + 58 km × $151 + 0,5 kg × $300",
    min: 2500,
    max: 21000,
  },
  {
    id: "price-buenos-aires-mar-del-plata-medium",
    type: "price",
    from: "Buenos Aires",
    to: "Mar del Plata",
    km: 414,
    parcel: "Caja mediana · 8 kg",
    price: 12680,
    breakdown: "$1.578 base + 414 km × $21 + 8 kg × $301",
    min: 2500,
    max: 112500,
  },
  {
    id: "price-mendoza-san-juan-small",
    type: "price",
    from: "Mendoza",
    to: "San Juan",
    km: 169,
    parcel: "Caja chica · 2 kg",
    price: 17560,
    breakdown: "$1.579 base + 169 km × $91 + 2 kg × $301",
    min: 17000,
    max: 61000,
  },
  {
    id: "price-san-miguel-de-tucuman-salta-fragile",
    type: "price",
    from: "San Miguel de Tucumán",
    to: "Salta",
    km: 304,
    parcel: "Frágil · 3 kg",
    price: 16222,
    breakdown: "($1.367 base + 304 km × $37 + 3 kg × $301) × 1,2 por frágil",
    min: 2500,
    max: 82500,
  },
  {
    id: "price-neuquen-bariloche-small",
    type: "price",
    from: "Neuquén",
    to: "Bariloche",
    km: 439,
    parcel: "Caja chica · 2 kg",
    price: 17680,
    breakdown: "$1.713 base + 439 km × $35 + 2 kg × $301",
    min: 20000,
    max: 157500,
  },
]

export const QUESTIONS_BY_ID = new Map(QUESTIONS.map((q) => [q.id, q]))
